"""principals classrooms enrollment

Revision ID: 5a5827bbaca2
Revises: e5fc345709b5
Create Date: 2026-07-27 21:11:21.202219
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5a5827bbaca2"
down_revision: str | None = "e5fc345709b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "principal",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("STUDENT", "TEACHER", "ADMIN", name="role", native_enum=False),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id"),
    )
    op.create_table(
        "classroom",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["principal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_classroom_teacher_id"), "classroom", ["teacher_id"], unique=False)
    op.create_table(
        "enrollment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("classroom_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["classroom.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("classroom_id", "student_id", name="uq_enrollment"),
    )
    op.create_index(
        op.f("ix_enrollment_classroom_id"), "enrollment", ["classroom_id"], unique=False
    )
    op.create_index(op.f("ix_enrollment_student_id"), "enrollment", ["student_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enrollment_student_id"), table_name="enrollment")
    op.drop_index(op.f("ix_enrollment_classroom_id"), table_name="enrollment")
    op.drop_table("enrollment")
    op.drop_index(op.f("ix_classroom_teacher_id"), table_name="classroom")
    op.drop_table("classroom")
    op.drop_table("principal")
    # ### end Alembic commands ###
