"""shadow candidates and ratings

Revision ID: 6b00a6ce9d57
Revises: 5a5827bbaca2
Create Date: 2026-07-27 22:18:07.198183
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6b00a6ce9d57"
down_revision: str | None = "5a5827bbaca2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shadow_candidate",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("hint_level", sa.Integer(), nullable=False),
        sa.Column("generated_text", sa.Text(), nullable=False),
        sa.Column("shown_text", sa.Text(), nullable=True),
        sa.Column("misconception_tag", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("leak_check_passed", sa.Boolean(), nullable=False),
        sa.Column("leak_checker_version", sa.String(length=64), nullable=False),
        sa.Column("leak_reason", sa.Text(), nullable=True),
        sa.Column("llm_call_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["llm_call_id"],
            ["llm_call.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shadow_candidate_prompt_version"),
        "shadow_candidate",
        ["prompt_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shadow_candidate_session_id"), "shadow_candidate", ["session_id"], unique=False
    )
    op.create_index(
        "ix_shadow_unrated", "shadow_candidate", ["created_at", "prompt_version"], unique=False
    )
    op.create_table(
        "shadow_rating",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shadow_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("better_than_shown", sa.Boolean(), nullable=False),
        sa.Column("would_leak", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["shadow_candidate_id"],
            ["shadow_candidate.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["principal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shadow_rating_shadow_candidate_id"),
        "shadow_rating",
        ["shadow_candidate_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shadow_rating_shadow_candidate_id"), table_name="shadow_rating")
    op.drop_table("shadow_rating")
    op.drop_index("ix_shadow_unrated", table_name="shadow_candidate")
    op.drop_index(op.f("ix_shadow_candidate_session_id"), table_name="shadow_candidate")
    op.drop_index(op.f("ix_shadow_candidate_prompt_version"), table_name="shadow_candidate")
    op.drop_table("shadow_candidate")
    # ### end Alembic commands ###
