"""safety alerts (P1.8)

The §7 welfare path: a signal raised from a child's own text, and proof that a
named adult read it. Two tables rather than a column on `review_item`, because a
teaching queue and a welfare alert have different readers and different
consequences for being missed — and `safety_acknowledgement` exists separately so
"nobody opened this" stays distinguishable from "someone looked and judged it
nothing", which is the only question worth asking of a safety path.

Revision ID: a922f431b2bd
Revises: 6b00a6ce9d57
Create Date: 2026-07-28 00:20:41.624793
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a922f431b2bd"
down_revision: str | None = "6b00a6ce9d57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "safety_alert",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "SELF_HARM",
                "HARM_FROM_OTHERS",
                "HOPELESSNESS",
                name="safety_category",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("screener_version", sa.String(length=64), nullable=False),
        sa.Column("classifier_ran", sa.Boolean(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_safety_alert_detected_at"), "safety_alert", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_safety_alert_session_id"), "safety_alert", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_safety_alert_student_id"), "safety_alert", ["student_id"], unique=False
    )
    op.create_table(
        "safety_acknowledgement",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("safety_alert_id", sa.Uuid(), nullable=False),
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("action_taken", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["safety_alert_id"],
            ["safety_alert.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_safety_acknowledgement_safety_alert_id"),
        "safety_acknowledgement",
        ["safety_alert_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_safety_acknowledgement_safety_alert_id"), table_name="safety_acknowledgement"
    )
    op.drop_table("safety_acknowledgement")
    op.drop_index(op.f("ix_safety_alert_student_id"), table_name="safety_alert")
    op.drop_index(op.f("ix_safety_alert_session_id"), table_name="safety_alert")
    op.drop_index(op.f("ix_safety_alert_detected_at"), table_name="safety_alert")
    op.drop_table("safety_alert")
    # ### end Alembic commands ###
