"""pipeline event log

Revision ID: e5fc345709b5
Revises: a86a106fe55f
Create Date: 2026-07-27 20:57:23.712276
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e5fc345709b5"
down_revision: str | None = "a86a106fe55f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "SESSION_STARTED",
                "STATE_CHANGED",
                "STAGE_STARTED",
                "STAGE_COMPLETED",
                "STAGE_FAILED",
                "FALLBACK_USED",
                "HINT_SHOWN",
                "ANSWER_SUBMITTED",
                "GRADED",
                "ESCALATED",
                "SESSION_COMPLETED",
                name="event_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "DIAGNOSE",
                "RERANK",
                "GENERATE_HINT",
                "LEAK_CHECK",
                "GRADE",
                "SAFETY_SCREEN",
                "TEACHER_SUMMARY",
                name="pipeline_stage",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "from_state",
            sa.Enum(
                "AWAITING_ANSWER",
                "DIAGNOSING",
                "RETRIEVING_CURRICULUM",
                "GENERATING_HINT",
                "LEAK_CHECKING",
                "AWAITING_STUDENT_RETRY",
                "GRADING",
                "COMPLETE",
                "ESCALATED",
                name="session_state",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_state",
            sa.Enum(
                "AWAITING_ANSWER",
                "DIAGNOSING",
                "RETRIEVING_CURRICULUM",
                "GENERATING_HINT",
                "LEAK_CHECKING",
                "AWAITING_STUDENT_RETRY",
                "GRADING",
                "COMPLETE",
                "ESCALATED",
                name="session_state",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("llm_call_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["llm_call_id"],
            ["llm_call.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "sequence", name="uq_event_sequence"),
    )
    op.create_index("ix_event_replay", "pipeline_event", ["session_id", "sequence"], unique=False)
    op.create_index(
        op.f("ix_pipeline_event_session_id"), "pipeline_event", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_event_session_id"), table_name="pipeline_event")
    op.drop_index("ix_event_replay", table_name="pipeline_event")
    op.drop_table("pipeline_event")
    # ### end Alembic commands ###
