import { chromium } from 'playwright'
const A = 'd47a9abd-66a3-49a4-b094-0baab2793f4d'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1400, height: 900 } })
p.on('pageerror', e => console.log('  PAGEERROR:', String(e).slice(0,300)))
p.on('console', m => console.log(`  console.${m.type()}: ${m.text().slice(0,250)}`))
p.on('response', r => { if (r.url().includes('/admin/') && r.status()>=400) console.log('  HTTP', r.status(), r.url()) })
await p.goto(`http://localhost:8080/admin/pipeline?as=${A}`, { waitUntil: 'networkidle' })
await p.waitForSelector('.run', { timeout: 20000 })
await p.locator('.run').first().click()
await p.waitForTimeout(4000)
console.log('  .tour count:', await p.locator('.tour').count())
console.log('  tour-host exists:', await p.locator('#tour-host').count())
console.log('  stage cards:', await p.locator('.stage').count())
console.log('  TOPOLOGY loaded:', await p.evaluate(() => TOPOLOGY ? TOPOLOGY.length : null))
console.log('  TOUR:', await p.evaluate(() => TOUR ? TOUR.stages.length + ' stages' : null))
await b.close()
